// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {model} from '../models';
import {kernel} from '../models';
import {store} from '../models';
import {session} from '../models';

export function AssignGroupBatch(arg1:Array<string>,arg2:string):Promise<app.BatchSummary>;

export function CheckProxy(arg1:model.Proxy):Promise<app.ProxyCheck>;

export function CreateProfile(arg1:app.CreateRequest):Promise<app.ProfileView>;

export function CreateShortcut(arg1:string):Promise<string>;

export function CredentialProtection():Promise<app.CredentialProtection>;

export function DefaultBatchConcurrency():Promise<number>;

export function DeleteBatch(arg1:Array<string>):Promise<app.BatchSummary>;

export function DeleteProfile(arg1:string):Promise<void>;

export function DeleteProfileData(arg1:string):Promise<void>;

export function DetectHostGPU(arg1:string):Promise<app.HostGPUInfo>;

export function ExportBundle(arg1:string,arg2:boolean):Promise<number>;

export function GetProfile(arg1:string):Promise<app.ProfileView>;

export function GroupTree():Promise<app.GroupTree>;

export function GroupUnassignedKey():Promise<string>;

export function ImportBundle(arg1:string,arg2:app.BundleImportOptions):Promise<app.BundleImportResult>;

export function ImportProxies(arg1:app.ImportRequest):Promise<app.ImportResult>;

export function InstallKernel(arg1:kernel.Release):Promise<kernel.Kernel>;

export function KernelsDir():Promise<string>;

export function ListAvailableKernels():Promise<Array<kernel.Release>>;

export function ListDeviceProfiles():Promise<Array<model.DeviceProfile>>;

export function ListKernels():Promise<Array<kernel.Kernel>>;

export function ListProfiles():Promise<Array<app.ProfileView>>;

export function ListSpoofTargets():Promise<Array<model.SpoofTarget>>;

export function OpenDefaultAppsSettings():Promise<void>;

export function ParseProxyLine(arg1:string):Promise<model.Proxy>;

export function PickExportPath():Promise<string>;

export function PickImportPath():Promise<string>;

export function QueryProfiles(arg1:store.Filter):Promise<Array<app.ProfileView>>;

export function RegisterURLHandler():Promise<void>;

export function RunningSessions():Promise<Array<session.Status>>;

export function SetURLHandler(arg1:string,arg2:boolean):Promise<void>;

export function StartBatch(arg1:Array<string>,arg2:number):Promise<app.BatchSummary>;

export function StartProfile(arg1:string):Promise<session.Status>;

export function StopBatch(arg1:Array<string>):Promise<app.BatchSummary>;

export function StopProfile(arg1:string):Promise<void>;

export function TagBatch(arg1:Array<string>,arg2:Array<string>,arg3:app.TagBatchMode):Promise<app.BatchSummary>;

export function URLHandler():Promise<app.URLHandlerView>;

export function UnregisterURLHandler():Promise<void>;

export function UpdateProfile(arg1:app.UpdateRequest):Promise<app.ProfileView>;
