// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AssignGroupBatch(arg1, arg2) {
  return window['go']['main']['App']['AssignGroupBatch'](arg1, arg2);
}

export function CheckProxy(arg1) {
  return window['go']['main']['App']['CheckProxy'](arg1);
}

export function CreateProfile(arg1) {
  return window['go']['main']['App']['CreateProfile'](arg1);
}

export function CreateShortcut(arg1) {
  return window['go']['main']['App']['CreateShortcut'](arg1);
}

export function CredentialProtection() {
  return window['go']['main']['App']['CredentialProtection']();
}

export function DefaultBatchConcurrency() {
  return window['go']['main']['App']['DefaultBatchConcurrency']();
}

export function DeleteBatch(arg1) {
  return window['go']['main']['App']['DeleteBatch'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function DeleteProfileData(arg1) {
  return window['go']['main']['App']['DeleteProfileData'](arg1);
}

export function DetectHostGPU(arg1) {
  return window['go']['main']['App']['DetectHostGPU'](arg1);
}

export function ExportBundle(arg1, arg2) {
  return window['go']['main']['App']['ExportBundle'](arg1, arg2);
}

export function GetProfile(arg1) {
  return window['go']['main']['App']['GetProfile'](arg1);
}

export function GroupTree() {
  return window['go']['main']['App']['GroupTree']();
}

export function GroupUnassignedKey() {
  return window['go']['main']['App']['GroupUnassignedKey']();
}

export function ImportBundle(arg1, arg2) {
  return window['go']['main']['App']['ImportBundle'](arg1, arg2);
}

export function ImportProxies(arg1) {
  return window['go']['main']['App']['ImportProxies'](arg1);
}

export function InstallKernel(arg1) {
  return window['go']['main']['App']['InstallKernel'](arg1);
}

export function KernelsDir() {
  return window['go']['main']['App']['KernelsDir']();
}

export function ListAvailableKernels() {
  return window['go']['main']['App']['ListAvailableKernels']();
}

export function ListDeviceProfiles() {
  return window['go']['main']['App']['ListDeviceProfiles']();
}

export function ListKernels() {
  return window['go']['main']['App']['ListKernels']();
}

export function ListProfiles() {
  return window['go']['main']['App']['ListProfiles']();
}

export function ListSpoofTargets() {
  return window['go']['main']['App']['ListSpoofTargets']();
}

export function OpenDefaultAppsSettings() {
  return window['go']['main']['App']['OpenDefaultAppsSettings']();
}

export function ParseProxyLine(arg1) {
  return window['go']['main']['App']['ParseProxyLine'](arg1);
}

export function PickExportPath() {
  return window['go']['main']['App']['PickExportPath']();
}

export function PickImportPath() {
  return window['go']['main']['App']['PickImportPath']();
}

export function QueryProfiles(arg1) {
  return window['go']['main']['App']['QueryProfiles'](arg1);
}

export function RegisterURLHandler() {
  return window['go']['main']['App']['RegisterURLHandler']();
}

export function RunningSessions() {
  return window['go']['main']['App']['RunningSessions']();
}

export function SetURLHandler(arg1, arg2) {
  return window['go']['main']['App']['SetURLHandler'](arg1, arg2);
}

export function StartBatch(arg1, arg2) {
  return window['go']['main']['App']['StartBatch'](arg1, arg2);
}

export function StartProfile(arg1) {
  return window['go']['main']['App']['StartProfile'](arg1);
}

export function StopBatch(arg1) {
  return window['go']['main']['App']['StopBatch'](arg1);
}

export function StopProfile(arg1) {
  return window['go']['main']['App']['StopProfile'](arg1);
}

export function TagBatch(arg1, arg2, arg3) {
  return window['go']['main']['App']['TagBatch'](arg1, arg2, arg3);
}

export function URLHandler() {
  return window['go']['main']['App']['URLHandler']();
}

export function UnregisterURLHandler() {
  return window['go']['main']['App']['UnregisterURLHandler']();
}

export function UpdateProfile(arg1) {
  return window['go']['main']['App']['UpdateProfile'](arg1);
}
